#!/usr/bin/env bash

SRC="https://raw.githubusercontent.com/colinmollenhour/modman/master/modman"
DEST="/usr/bin/modman"

# test if curl/wget is installed
if hash curl 2>&- ; then
    CMD="curl -s -L $SRC -o $DEST"
elif hash wget 2>&- ; then
    CMD="wget -q --no-check-certificate -O $DEST $SRC"
else
   echo "You need to have curl or wget installed."
   exit 1
fi

$CMD

chmod +x $DEST

echo
echo "Done. Modman installed in $HOME/bin/modman"
echo
